{
  "hash": "33375566968dd1ebc0ae1a9983be6904",
  "result": {
    "markdown": "# Estymacja punktowa i przedziałowa\n\n**Estymacja** to oszacowanie (z pewną dokładnością) na podstawie próby wartości badanej cechy statystycznej (np. średniej) oraz rozciągnięcie otrzymanych wyników na całą populację.\n\n![](figures/7_est.png)\n\n## Podstawowe pojęcia\n\n-   **Rozkład próby**\n\n-   **Błąd standardowy** (ang. *Standard Error*) danej statystyki (miary, np. średniej) - odchylenie standardowe rozkładu wartości z próby\n\n-   **Prawo wielkich liczb** (ang. *law of large numbers - LLN*) - teoria mówiąca, iż zwiększając liczbę doświadczeń opartych na zdarzeniach losowych, możemy oczekiwać rozkładu wyników (próba) coraz lepiej odpowiadającego rozkładowi prawdopodobieństw zdarzeń (populacja) oraz, iż tym większe są na to szanse im większa jest liczba doświadczeń\n\n-   **Centralne twierdzenie graniczne** (ang. *central limit theorem - CLT*) - teoria mówiąca, iż średnia wystarczająco dużego zbioru liczb niezależnych prób losowych, każdych ze skończoną średnią i wariancją, będzie posiadała w przybliżeniu rozkład normalny\n\n    -   https://gallery.shinyapps.io/CLT_mean/\n    -   https://ihstevenson.shinyapps.io/sample_means/\n\n## Estymacja punktowa\n\n-   ustalenie wartości liczbowej nieznanego parametru (np. średniej) na podstawie wyników próby.\n-   dla każdej próby losowej liczymy wartość średnią.\n-   zazwyczaj wartość średnia wyliczona z próby nie będzie zgodna z wartością średnią dla populacji.\n\n## Estymacja przedziałowa\n\n-   Numeryczne podsumowanie niepewności estymacji\n\n-   Wyznaczamy pewien przedział liczbowy, który z pewnym prawdopodobieństwem zawiera wartość nieznanego parametru. Przedział taki nazywany jest ***przedziałem ufności***.\n\n    -   Np. 95% przedział ufności mówi, że dla 95% z próby, ten przedział zawiera poprawną wartość\n\n### Przedział ufności\n\n-   zakres możliwych wartości dla nieznanej średniej populacji oparty na danych próby\n-   wyliczany jest dla oszacowania wartości pewnej charakterystyki populacji (np. średniej arytmetycznej) na podstawie próby.\n-   wartość charakterystki (np.średniej) wyliczona z próby, będzie się nieco róźnić od tej dla całej populacji.\n-   gdy próba jest reprezentatywna możemy oczekiwać niezbyt dużych różnic między rzeczywistą wartością charakterystyki dla populacji, a wyznaczoną z próby. **PODSUMOWUJĄC: Przedział ufności określa nam prawdopodobny zakres odchylenia naszych wyliczeń od wartości rzeczywistej.**\n\n**Interpretacja**\n\n-   Jeśli wielokrotnie z wielu niezależnych prób losowych będziemy wyznaczali przedziały, to $100(1-\\alpha)%$ (np. 95%) takich przedziałów będzie zawierało prawdziwą wartość parametru.\n\n-   Zatem przy dużej liczbie powtórzeń zdanie \"Prawdziwa wartość parametru mieści się w przedziale ufności\" będzie prawdziwe w $100(1-\\alpha)%$ powtórzeń.\n\n-   Często (choć mniej precyzyjnie) przedział ufności określany jest zdaniem: \"z 95% prawdpopodobieństwem przedział zawiera wartość parametru\"\n\n**Przykład:**\n\n-   Tworzymy próbę z 25 obserwacjami z rozkładu normalnego o średniej 10 i odchyleniu standardowym 2. Wyliczamy 95% przedział ufności. Powtarzamy to stukrotnie. Kolorem czarnym zaznaczono przedziały, które zawierają średnią, innym kolorem te które średniej nie zawierają.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](6a_wnioskowanie_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n> Wykonaj powyższe obliczenie przy założeniu 90% oraz 99% poziomu ufności.\n\nFunkcja ta pozwala na definiowanie przedziału ufności za pomocą suwaka i interaktywne wprowadzanie zmian.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(TeachingDemos)\nif(interactive()) {\n  run.ci.examp()\n}\n```\n:::\n\n\n### Obliczanie przedziału ufności (CI)\n\n1.  Założenia\n\n    -   Dane próby są próbą losową z populacji (każda wartość ma takie same szanse wylosowania)\n    -   Rozkład danych populacji jest normalny (trzeba pamiętać, że określenie normalności rozkładu nie może być kompletne bez posiadania danych całej populacji)\n\n2.  Wyznaczenie CI\n\n    -   zdefiniowanie parametru populacji (np. średnia)\n    -   określeniu poziomu ufności - wartość od 0 do 100% (zazwyczaj 95 lub 99%)\n    -   wyliczenie wartości krytycznych rozkładu t-Studenta (stosowany, gdy nie znamy odchylenia standardowego populacji) lub rozkładu normalnego (gdy znamy odchylenie standardowe populacji)\n    -   podanie wartości przedziału, np. w postaci (dolna granica, gorna granica)\n\nPrzedział ufności dla średniej ma postać $Średnia \\pm Zakres błędu$ ( $Mean \\pm Margin of error$ )\n\n## Estymacja parametrów w R\n\nEstymacja parametrów w R zostanie omówiona na przykładzie danych `survey` z pakietu MASS. Zbiór ten zawiera wyniki badania studentów z Australijskiego uniwersytetu, którzy udzielali odpowiedzi na różne pytania.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nhead(survey) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Sex Wr.Hnd NW.Hnd W.Hnd    Fold Pulse    Clap Exer Smoke Height      M.I\n1 Female   18.5   18.0 Right  R on L    92    Left Some Never 173.00   Metric\n2   Male   19.5   20.5  Left  R on L   104    Left None Regul 177.80 Imperial\n3   Male   18.0   13.3 Right  L on R    87 Neither None Occas     NA     <NA>\n4   Male   18.8   18.9 Right  R on L    NA Neither None Never 160.00   Metric\n5   Male   20.0   20.0 Right Neither    35   Right Some Never 165.00   Metric\n6 Female   18.0   17.7 Right  L on R    64   Right Some Never 172.72 Imperial\n     Age\n1 18.250\n2 17.583\n3 16.917\n4 20.333\n5 23.667\n6 21.000\n```\n:::\n:::\n\n\nWięcej informacji o zbiorze danych znajduje się w dokumentacji\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhelp(survey)\n```\n:::\n\n\n### Estymacja punktowa średniej z populacji.\n\nBadanie zostało przeprowadzone na próbie 237 studenów. Możemy obliczyć średnią z próby, którą będziemy traktować jako oszacowanie średniej populacji.\n\n**Problem: Oszacować średni wzrost studentów uniwersytetu na podstawie danych z próby**\n\n**Rozwiązanie:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Przypisanie wzrostu studentów do zmiennej wzrost\nwzrost <- survey$Height\n```\n:::\n\n\nObliczenie średniego wzrostu na podstawie wyników badania. Argument na.rm = TRUE jest konieczny - nie wszyscy studenci odpowiedzieli na to pytanie.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(wzrost, na.rm=TRUE)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 172.3809\n```\n:::\n:::\n\n\n**Odpowiedź:**\n\nŚredni wzrostu studentów wynosi 172,38 cm.\n\n### Wyznaczenie przedziałów ufności dla średniej znając odchylenie standardowe (SD)\n\nW poprzednim przykładzie określona została wartość średniej na podstawie próby. W tym przykładzie wyznaczymy *przedział ufności* - który określi nam z jaką \"dokładnością\" oszacowaliśmy wartość średniej.\n\nPrzy założeniu, że odchylenie standardowe jest znane do wyznaczenia przedziału, w jakim znajduje się wartość średnia, możemy posłużyć się wzorem:\n\n$$\\overline{x} \\pm z_{\\alpha/2} \\frac{\\sigma} {\\sqrt{n}}$$\n\ngdzie, $z_{\\alpha/2}$ oznacza 100(1-$\\alpha$) percentyl standaryzowanego rozkładu normalnego.\n\n**Problem**\n\nZałóżmy, że odchylenie standardowe populacji $\\sigma$ dla wzrostu studentów wynosi 9.48. Znajdź zakres błędu (ang. *margin of error*) oraz przedział, w którym znajduje się średnia przy założeniu 95% poziomu ufności.\n\n**Rozwiązanie:**\n\nObliczamy błąd standardowy średniej:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwzrost <- na.omit(survey$Height)\nn <- length(wzrost) \nsigma <- 9.48            # odchylenie standardowe populacji\nsem <- sigma/sqrt(n)   # błąd standardowy średniej\nsem         #błąd standardowy średniej\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6557453\n```\n:::\n:::\n\n\nObliczamy zakres błędu.\n\nPrzyjmujemy poziom ufności $1-\\alpha = 0.95$ (95%). Zatem $\\alpha=0.05$, a $\\alpha/2=0.025$. Zatem $z_{\\alpha/2}$ obliczyć można za pomocą funkcji `qnorm(0.025, lower.tail = FALSE)` (statystyka z oznacza, że przyjmujemy rozkład normalny). Jeśli wynik wymnożymy przez błąd standardowy średniej (sem) uzyskamy zakres błędu (ang. *margin of error*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE = qnorm(0.025, lower.tail = FALSE) * sem   # zakres błędu\nE #zakres błędu\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.285237\n```\n:::\n:::\n\n\nNastępnie wartość błędu dodajemy do średniej i otrzymujemy przedział ufności:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsr_wzrost <- mean(wzrost)   # średnia próby\nsr_wzrost + c(-E, E)  # przedzial ufności\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 171.0956 173.6661\n```\n:::\n:::\n\n\n**Odpowiedź:**\n\nZakładając, że odchylenie standardowe populacji jest równe 9.48 to zakres błędu w ocenie wzrostu studentów przy 95% poziom ufności wynosi 1,2852 cm. Przedział ufności jest pomiędzy 171.10 a 173.67 cm.\n\n> Znajdź przedział, w którym znajduje się średnia przy założeniu 99% poziomu ufności.\n\n\n::: {.cell}\n\n```{.r .fold-hide .cell-code}\n#Wartosc sem nie zmieni się, sem = sigma/sqrt(n)\nwzrost <- na.omit(survey$Height)\nsem = 9.48/sqrt(length(wzrost))\n#Zakladamy 99% poziom ufnosci, zatem 1-alfa=0.99, alfa=0.01, alfa/2=0.005, \nE = qnorm(0.005, lower.tail = FALSE) * sem \nsrednia<- mean(wzrost)\nci <- srednia + c(-E, E)  # przedzial ufności\n```\n:::\n\n\n### Wyznaczanie przedziałów ufności dla średniej populacji nieznając odchylenia standardowego (SD)\n\nPrzy założeniu, że odchylenie standardowe jest nieznane do wyznaczenia przedziału, w jakim znajduje się wartość średnia, możemy posłużyć się wzorem:\n\n$$\\overline{x} \\pm t_{\\alpha/2} \\frac{s} {\\sqrt{n}}$$\n\ngdzie, $t_{\\alpha/2}$ oznacza 100(1-$\\alpha$) percentyl rozkładu t-Studenta z n-1 stopni swobody.\n\n**Problem**\n\nZnajdź zakres błędu (ang. *margin of error*) oraz przedział ,w którym znajduje się średnia przy założeniu 95% poziomu ufności oraz zakładając, że odchylenie standardowe populacji jest nieznane.\n\n**Rozwiązanie**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)                  # load the MASS package \nwzrost <- na.omit(survey$Height)\nn = length(wzrost) \ns = sd(wzrost)        # odchylenie standardowe próby\nSE = s/sqrt(n) \nSE             #szacowany błąd standardowy średniej (standard error estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6811677\n```\n:::\n:::\n\n\nObliczenie zakresu błędu\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE = qt(0.025, df=n-1, lower.tail = FALSE) * sem \nE     # zakres błędu margin of error \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.292759\n```\n:::\n:::\n\n\nNastępnie wartość błędu dodajemy do średniej i otrzymujemy przedział ufności:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsr_wzrost <- mean(wzrost)   # średnia próby\nsr_wzrost + c(-E, E)  # CI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 171.0881 173.6736\n```\n:::\n:::\n\n\n**Odpowiedź**\n\nPrzy założeniu, że odchylenie standardowe z populacji jest nienznane to zakres błędu w ocenie wzrostu studentów przy 95% poziom ufności wynosi 1.3429 cm. Przedział ufności jest pomiędzy 171.04 a 173.72 cm.\n\n> Znajdź przedział, w którym znajduje się średnia przy założeniu 99% poziomu ufności (i nieznanym odchyleniu standardowym populacji)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Kod R\"}\n#Wartosc sem nie zmieni się, sem = sigma/sqrt(n)\nwzrost <- na.omit(survey$Height)\nSE = sd(wzrost)/sqrt(length(wzrost))\n#Zakladamy 99% poziom ufnosci, zatem 1-alfa=0.99, alfa=0.01, alfa/2=0.005, prcentyl=0.99+0.005=0.995\nE = qt(0.005, df=length(wzrost)-1)*SE # zakres błędu\nsrednia<- mean(wzrost)\nci <- srednia + c(-E, E)  # przedzial ufności\n```\n:::\n\n\n> Zadanie: Zebraliśmy losową próbę, pytając 10 studentów z wybranego kierunku, którzy skończyli studia w 2019 roku, jakie są ich roczne zarobki. Otrzymaliśmy odpowiedź: x = c(44617, 7066, 17594, 2726, 1178, 18898, 5033, 37151, 4514, 4000). Oszacuj średnie zarobki wszystkich studentów studiujących na tym kierunku, którzy ukończyli studia w 2019 roku. Określ także 90 oraz 95% przedział ufności dla średniej. 1) Wykonaj obliczenia, zakładając, że zarobki mają rozkład normalny, z odchyleniem standardowym 15000. 2) Wykonaj obliczenia przy nieznanym odchyleniu standardowym.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Kod R\"}\n#dane \nx <- c(44617, 7066, 17594, 2726, 1178, 18898, 5033, 37151, 4514, 4000)\n# OBLICZENIA PRZY ZNANYM SD\nsrednia <- mean(x)\n\n#blad standardowy sigma/sqrt(n), sigma to znane odchylenie standardowe a n to liczba elementów w probie\nse <- 15000/10\n\n#z(alfa/2) 1-alfa = 0.95, alfa=0.05, alfa/2=0.025, \n#wykonujac obliczenia dla 99% poziomu ufnosci zamiast 0.025 nalezy wpisac 0.005\nE = qnorm(0.025, lower.tail = FALSE)*se \nci = srednia + c(-E, E)\n\n# odpowiedz: Srednie zarobki beda w przedziale 11338 a 17218 przy zalozeniu 95% poziomu ufnosci. \n# odpowiedz: Srednie zarobki beda w przedziale 10414 a 18141 przy zalozeniu 99% poziomu ufnosci. \n\n# OBLICZENIA PRZY NIEZNANYM SD \n#jesli nieznamy sd to musimy oszacowac jego wartosc na podstawie proby \ns = sd(x)\nsrednia = mean(x)\nn = 10\nSE = s/n\n\n#zakres bledu przy nieznanym odchyleniu standardowym obliczamy korzystajac z rozkladu t-studenta \n#wykonujac obliczenia dla 99% poziomu ufnosci zamiast 0.025 nalezy wpisac 0.005\nE = qnorm(0.025, lower.tail = FALSE)*SE\nci = srednia + c(-E, E)\n\n# odpowiedz: Srednie zarobki beda w przedziale 11270 a 17285 przy zalozeniu 95% poziomu ufnosci. \n# odpowiedz: Srednie zarobki beda w przedziale 10325 a 18231 przy zalozeniu 99% poziomu ufnosci. \n\n# Zauwaz, ze Zwiększanie poziomu ufności powoduje zwiększanie szerokości przedziału ufności - czyli zmniejszenie precyzji estymacji. \n```\n:::\n",
    "supporting": [
      "6a_wnioskowanie_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}